# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='avg_hr',
            field=models.FloatField(blank=True),
        ),
    ]
